---
title: ""
author: "Shaw Kagawa"
date: "12/18/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(dbplyr)
library(DBI)
library(magrittr)
library(tidyverse)
library(plotly)
library(shiny)

db_file <- "stop_times.db"
con <- DBI::dbConnect(RSQLite::SQLite(), db_file)

stop_times <- tbl(con, "stop_times")
```

```{r, echo=FALSE}
inputPanel(
        dateInput("dateInput", 
                  label="Select a Date:",
                  min="2018-12-01",
                  max=as.character(Sys.Date()),
                  language="EN",
                  value=as.character(Sys.Date())),
        sliderInput("binwidth",
                    "Bin Width:",
                    min=1, max=100,
                    value=1,
                    step=1)
)

renderPlotly({
        dateChar <- as.character(
                as.Date(input$dateInput, origin="1970-01-01"))
        stop_times %>%
                ggplot(aes_string(x=as.symbol(dateChar))) + 
                        geom_histogram(binwidth=input$binwidth) +
                        labs(x="Delay", y="Count",
                             title=paste0("Delays for all buses on ", dateChar))
})

inputPanel(
        selectInput("routeId",
                    label="Select a bus route:",
                    choices=stop_times %>%
                            distinct(route_id) %>%
                            pull(route_id),
                    selected="ILLINI"
        )
)

renderPlotly({
        dateChar <- as.character(
                as.Date(input$dateInput, origin="1970-01-01"))
        stop_times %>%
                filter(route_id==input$routeId) %>%
                ggplot(aes_string(x=as.symbol(dateChar))) +
                        geom_histogram(binwidth=1) + 
                        labs(x="Delay", y="Count",
                             title=paste0("Delays for ", input$routeId, " on ", dateChar))
})
```

